services:
    victoire_core.widget_mailchimpnewsletter_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: MailchimpNewsletter }

    #alias to the entity
    victoire.widget.mailchimpnewsletter:
        class: Victoire\Widget\MailchimpNewsletterBundle\Entity\WidgetMailchimpNewsletter

    #alias to the form
    victoire.widget.form.mailchimpnewsletter:
        class: Victoire\Widget\MailchimpNewsletterBundle\Form\WidgetMailchimpNewsletterType
        arguments:
          - @hype_mailchimp
        tags:
            - { name: form.type }
